### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by Zhentao-Liu** [eth-ait/GaussianHaircut#1]
Wonderful work.
Hope early release of your code.

**Comment by egorzakharov** [comment]
Thanks for your interest! Eta for the code is 2 weeks

**Comment by Zhentao-Liu** [comment]
wonderful and thanks



---Original---
From: "Egor ***@***.***&gt;
Date: Sun, Sep 29, 2024 19:59 PM
To: ***@***.***&gt;;
Cc: "Zhentao ***@***.******@***.***&gt;;
Subject: Re: [eth-ait/GaussianHaircut] Code release (Issue #1)




 
Thanks for your interest! Eta for the code is 2 weeks
