### ISSUE TITLE
  windows系统

### ISSUE THREAD

**Issue by zhumengmeng1221** [eth-ait/GaussianHaircut#4]
I am using a Windows system and Python environment. What should I install

**Comment by egorzakharov** [comment]
The code does not support Windows. I don't think I have time to create and debug instructions for the project to run for Windows. If you figure it out -- make a pull request for the readme, and I'll add it to the instructions.

Here are some tips.

The biggest issue with the reconstruction part is the pytorch3d compilation, which may break under WSL. Pre-processing may become easier as there are OpenPose binaries for Windows.
