### ISSUE TITLE
Exporting Strands to Unreal

### ISSUE THREAD

**Issue by SrinjaySarkar** [eth-ait/GaussianHaircut#5]
Hi , thank you for replying to my previous issue. Could you please describe the process that you used to import the rendered strands from the video into Unreal ?

**Comment by egorzakharov** [comment]
Hi! 

To proceed with the simulation, you'll first need to remove the intersections of the strands with the head mesh. 

You can do it by pruning the strands that intersect the mesh (we did that for the hairstyles we've shown in the paper), but that doesn't work with too many intersections. 

IIRC, GrromGen has proposed another solution where they iteratively push the strands out of the head scalp, which has more robustness: https://arxiv.org/abs/2311.02062

I'll ask Joachim to respond with the details on the Unreal side, as he created these simulations.

**Comment by Vanessik** [comment]
Hi @SrinjaySarkar, 
to obtain hair simulations in Unreal you need to convert the obtained .ply hairstyle into .abc file using [export_for_unreal.py](https://github.com/Vanessik/HAAR/blob/master/src/utils/export_for_unreal.py), then import it into Unreal and attach to an object, which will drive simulations. 
For more details please follow [UnrealEngine docs](https://dev.epicgames.com/documentation/en-us/unreal-engine/hair-simulation-and-rendering-quick-start-guide-in-unreal-engine?application_version=5.2).

**Comment by LarkLeeOnePiece** [comment]
Hi, I have a question about the simulation in Unreal. Did you render the hair Gaussian in Unreal or you only export  the Hair vertices geometry to Unreal and use other way the render the appearance of the Hair?
