### ISSUE TITLE
Installation environment and procedure

### ISSUE THREAD

**Issue by LiuZixu-aurelio** [eth-ait/GaussianHaircut#6]
hi,

1. Is the environment Linux? and Are there any requirements for the version?
2. Whether the hardware has requirements, CPU, GPU or RAM？
3. Is it necessary to install blender？For example The exported ply is visually rendered on another computer or another Application

Thx Regards

**Comment by egorzakharov** [comment]
Hi

1. Yes. Any Linux LTS should work. For preliminary dependencies, such as OpenPose, please consult their respective repos
2. GPU, 24 GB memory. The code was tested on RTX 4090, RTX 6000 and A100
3. No, the visualization portion of the script is run only at the end

**Comment by egorzakharov** [comment]
Let me know if you encounter any installation issues, so that we could update the requirements or update the installation config to make it more general.

**Comment by LiuZixu-aurelio** [comment]
when I run install.sh, This pytorch or cuda version does not appear to be compatible, Error reported: only CPU can be used.
<img width="734" alt="image" src="https://github.com/user-attachments/assets/6fbda34b-2c3d-4189-80fb-74667ccd3a13">

**Comment by localhost-server** [comment]
I would recommend to use Ubuntu 20.04 and install cuda from https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network and while installing cuda use (sudo apt-get -y install cuda-11-8) .
