### ISSUE TITLE
Training my own data, the results obtained will also have hair strands on the body

### ISSUE THREAD

**Issue by nanase111** [eth-ait/GaussianHaircut#9]
![000006](https://github.com/user-attachments/assets/83444991-58d8-4d87-a472-2fe8934e583f)
Thanks for your great work.
When I train my data, I encountered this probem. Is there any solution to solve this? My gaussian rendered head mask and hair mask seemed to be right, but the final results, strand gaussians will also reconstruct in the body area.

**Comment by localhost-server** [comment]
Hi I am facing an issue https://github.com/eth-ait/GaussianHaircut/issues/11#issue-2624475549 can you please check and let us know the reason for this

**Comment by autolife-nz** [comment]
@nanase111 would love to ask you a question about your Gaussian hair install setup. Can you email me on the email in my profile if you are able to help. Thank you!
